19.10.2021. Create a prototipe of reply algorithm
AlienFoun/Marcus pull request #2
Opened 2021-10-18 22:40 UTC by AlienFoun

2021-10-19 06:10 UTC, coolswood requested changes

2021-10-19 06:10 UTC, coolswood commented on helper.py
> +def database_loads(cur) -> List[List[str]]:
Похоже это должно быть в файле с базой данных

2021-10-19 06:10 UTC, coolswood commented on reply.py
> +                           ]
Не очень понял зачем здесь этот лист, у тебя же он есть в базе, формируй его в рантайме из нее

2021-10-19 06:10 UTC, coolswood commented on helper.py
> +    return weight_list
Слабо понимаю как это работает, кажется не очень верно, давай тесты на эту функцию

2021-10-19 06:10 UTC, coolswood commented on sql.py
> +        print('При обновлении базы данных произошла ошибка')
Давай сразу писать вывод ошибок на английском

2021-10-19 06:10 UTC, coolswood commented on reply.py
> +def reply_output(text: str, data: List) -> List[str]:
`data` слишком общее название, непонятно что это за данные

2021-10-19 06:10 UTC, coolswood commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', ['я', 'тебя', 'люблю', 'я тебя', 'тебя люблю',
Я так понимаю, что второй параметр это данные из базы, мы же хотели хранить там слова с весом, не очень понимаю как в текущей реализации это должно работать
Можешь скинуть как выглядит структура бд?

2021-10-19 06:10 UTC, coolswood commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', '']]), [])
Хорошо, что добавил тесты на эту функцию, она важная, но думаю их потребуется тут больше, потому что тут ты уже имеешь дело с пользовательским вводом. Может придти что угодно
Можно посмотреть как твоя функция отработает такие варианты напирмер
`ывппвыыва ываывавыоадл`
`2342324 234234 333` (это строка)

2021-10-19 08:38 UTC, AlienFoun commented on helper.py
> +def database_loads(cur) -> List[List[str]]:
Да, поправил

2021-10-19 08:50 UTC, AlienFoun commented on reply.py
> +                           ]
Поправил

2021-10-19 09:09 UTC, AlienFoun commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', ['я', 'тебя', 'люблю', 'я тебя', 'тебя люблю',
Мы же решили, вроде, позже добавить систему весов, поэтому тут пока их нет

2021-10-19 09:13 UTC, AlienFoun commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', ['я', 'тебя', 'люблю', 'я тебя', 'тебя люблю',
![image](https://user-images.githubusercontent.com/46862907/137880037-f19d05e1-e044-473a-8c7e-56275b97f126.png)

2021-10-19 09:45 UTC, AlienFoun commented on sql.py
> +        print('При обновлении базы данных произошла ошибка')
Поправил

2021-10-19 09:45 UTC, AlienFoun commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', '']]), [])
Добавил

2021-10-19 09:46 UTC, AlienFoun commented on reply.py
> +def reply_output(text: str, data: List) -> List[str]:
Поправил

2021-10-19 10:07 UTC, AlienFoun commented on helper.py
> +    return weight_list
Сделал

2021-10-19 10:09 UTC, AlienFoun commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', ['я', 'тебя', 'люблю', 'я тебя', 'тебя люблю',
После добавления системы весов, поменяю немного функцию found_duplication, чтобы прибавлялась не 1, а вес фрагмента

2021-10-19 10:13 UTC, coolswood commented on unittests.py
> +        self.assertEqual(reply_output('', [['due', ['я', 'тебя', 'люблю', 'я тебя', 'тебя люблю',
окей

2021-10-20 14:38 UTC, coolswood requested changes

2021-10-20 14:38 UTC, coolswood commented on helper.py
> +    rows = sql_fetch(cursor, tag_name)  # Получаем значения из базы для конкретной ошибки в формате json в виде списка
Не очень хорошо прокидывать сюда `cursor`, в helper должны быть чистые функции, rows нужно сюда на вход передавать
Если оставишь так, будет сложно тестировать эту функцию

2021-10-20 14:38 UTC, coolswood commented on helper.py
> +    if rows == []:  # Если для конкретной ошибки пустой вывод, то этой ошибки нет в базе
Вот это задача кажется не для этой функции, когда работа с базой будет вынесена из этой функции данный функционал тоже стоит вынести в другую функцию

2021-10-20 14:38 UTC, coolswood commented on helper.py
> +def words_list_gen(lists: dict, tag_dict: dict) -> dict:
Функция достаточно сложная и важная для написания тестов

2021-10-20 14:38 UTC, coolswood commented on helper.py
>      return clear_text
Может упростить этот код до `return clear_text.strip(string.punctuation)` ?

2021-10-20 14:38 UTC, coolswood commented on helper.py
> +    if text != ['']:  # Проверка входных данных
Лучше будет читаться, если проверки на валидность данных будут делаться в начале файла

```
if text == [''] return {}
text_dict = {}  # Создаем словарь, в котором будут храниться слова + их вес
        for value in text:
            new_values = {value: (len(value) // 5) + 1}  # Создаем переменную для обновления словаря в виде: {слово: вес}
            text_dict.update(new_values)  # Обновляем словарь
        return text_dict
```

2021-10-20 16:40 UTC, AlienFoun commented on helper.py
> +    if text != ['']:  # Проверка входных данных
Поправил

2021-10-20 16:44 UTC, AlienFoun commented on helper.py
>      return clear_text
Да, я тоже так думаю, но почему-то подумал, что будет не совсем правильно

2021-10-20 16:44 UTC, AlienFoun commented on helper.py
> +    if rows == []:  # Если для конкретной ошибки пустой вывод, то этой ошибки нет в базе
Поправил

2021-10-20 16:44 UTC, AlienFoun commented on helper.py
> +    rows = sql_fetch(cursor, tag_name)  # Получаем значения из базы для конкретной ошибки в формате json в виде списка
Поправил

2021-10-20 17:36 UTC, AlienFoun commented on helper.py
> +def words_list_gen(lists: dict, tag_dict: dict) -> dict:
Поправил

2021-10-21 08:05 UTC, coolswood commented
@AlienFoun Можно мержить

2021-10-21 08:07 UTC, merged